# Generated by Django 2.2.6 on 2020-01-06 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('s_date', models.DateField(default=datetime.date.today)),
                ('e_date', models.DateField(default=datetime.date.today)),
                ('intro', models.TextField(max_length=500)),
                ('role', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('d_b', models.CharField(max_length=30)),
                ('ides', models.CharField(max_length=30)),
            ],
        ),
    ]
